server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:mem:notekeeper
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: my-very-secret-key-12345678901234567890123456789012
  expiration: 86400000  # 1 day in ms
